[versions]
geyser = "preview-feature-26.2-SNAPSHOT"
shadow = "9.5.1"
architectury-plugin = "3.5-SNAPSHOT"
architectury-loom = "1.17-SNAPSHOT"
minecraft-version = "26.2"
minotaur = "2.+"
lombok = "9.5.0"
mixin = "0.8.7"
configurate = "4.2.0"
typesafe = "1.4.9"
geantyref = "2.0.1"
asm = "5.2"
floodgate = "2.2.5-SNAPSHOT"

# Fabric
fabric-loader = "0.19.3"
fabric-api = "0.154.2+26.2"

# NeoForge
neoforge-version = "26.2.0.8-beta"

[libraries]
geyser-api = { group = "org.geysermc.geyser", name = "api", version.ref = "geyser" }
floodgate-api = { group = "org.geysermc.floodgate", name = "api", version.ref = "floodgate" }
shadow = { group = "com.gradleup.shadow", name = "com.gradleup.shadow.gradle.plugin", version.ref = "shadow" }
architectury-plugin = { group = "architectury-plugin", name = "architectury-plugin.gradle.plugin", version.ref = "architectury-plugin" }
architectury-loom = { group = "dev.architectury.loom-no-remap", name = "dev.architectury.loom-no-remap.gradle.plugin", version.ref = "architectury-loom" }
minotaur = { group = "com.modrinth.minotaur", name = "Minotaur", version.ref = "minotaur" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
asm = { group = "org.ow2.asm", name = "asm-debug-all", version.ref = "asm" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft-version" }
configurate-hocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
configurate-core = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
typesafe = { group = "com.typesafe", name = "config", version.ref = "typesafe" }
geantyref = { group = "io.leangen.geantyref", name = "geantyref", version.ref = "geantyref" }

# Fabric
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

# NeoForge
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge-version" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }