name: Publish

on:
  workflow_dispatch:
  push:
   paths-ignore:
     - '.gitignore'
     - 'LICENSE.md'
     - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@e8d4307400f9427dba7cb98e488d6ab85f1cec5f

      - name: Change Gradle Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@6550634d3eb14a20275549de1588a83267023d42

      - name: Setup JDK
        uses: actions/setup-java@fe9b749bcb36d9ac2a6c2cb1737d49b80e57ea06
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Build Hurricane-Modded
        run: ./gradlew build

      - name: Archive Artifacts (Hurricane-Fabric)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: success()
        with:
          name: Hurricane-Fabric
          path: fabric/build/libs/hurricane-fabric.jar
          if-no-files-found: error

      - name: Archive Artifacts (Hurricane-NeoForge)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: success()
        with:
          name: Hurricane-NeoForge
          path: neoforge/build/libs/hurricane-neoforge.jar
          if-no-files-found: error

      - name: Publish to Modrinth (Hurricane-Fabric)
        if: ${{ success() && github.repository == 'onebeastchris/Hurricane-Modded' && github.ref_name == '26.2' }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew fabric:modrinth

      - name: Publish to Modrinth (Hurricane-NeoForge)
        if: ${{ success() && github.repository == 'onebeastchris/Hurricane-Modded' && github.ref_name == '26.2' }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew neoforge:modrinth